kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ms-test
  namespace: namespace-backend # Simona - Update the namespace post cluster creation.
  labels:
    application: ms-test
spec:
  lookupPolicy:
    local: false